### ISSUE TITLE
Cmds staff

### ISSUE THREAD

**Issue by xSphere1** [Nonolanlan1007/Yop-Bot#1]
i found all cmds have this issue kick, ban, unban, warn, invitegen, mute, unmute ![Capture](https://user-images.githubusercontent.com/67423351/140729587-2b094d57-b204-45cc-a054-8cfe1872a762.PNG)

**Comment by Nonolanlan1007** [comment]
Hi, what's your bot's version ?

**Comment by SpaceLeft** [comment]
> Hi, what's your bot's version ?

3.3

**Comment by Nonolanlan1007** [comment]
I'll watch this.

**Comment by ValRedstone** [comment]
Hello, all commands have been fixed.

**Comment by ValRedstone** [comment]
Bugs fixed
