### ISSUE TITLE
bug accept et reject

### ISSUE THREAD

**Issue by iTazzz** [Nonolanlan1007/Yop-Bot#2]
Quand on accepte un bot ou refuse une erreur a propos de verifications, et du coup les rôles ne s'ajoute plus du tout, et pour le reject le menu pour avertir l'utilisateur ne s'envoie pas

![image](https://user-images.githubusercontent.com/62267574/141122416-28ca7ee7-0a42-4a45-b448-268c5296f50b.png)

**Comment by Nonolanlan1007** [comment]
Envoie : 
`y!e const user= require("../../models/user")
new user({
userID: "id du vérificateur",
verifications: 0
}).save()`

Pour l'instant, je ne me suis pas encore penché sur la question.
